version: '3.6'
services:

  viewer:
    image: ohif/viewer:v4.9.8.14493
    container_name: viewer
    depends_on:
      - orthanc
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./html:/usr/share/nginx/html
      # Nginx as a reversed proxy for orthanc and the viewer
      - ${NGINX_DEFAULT_CONF}:/etc/nginx/conf.d/default.conf:ro
      # OHIF Viewer configuration to reach DICOMWeb endpoints
      - ${VIEWER_CONFIG}:/usr/share/nginx/html/app-config.js:ro


  orthanc:
    image: osimis/orthanc:21.5.2
    container_name: orthanc
    depends_on:
      - postgres
    restart: always
    ports:
      - '4242:4242'
    volumes:
      # configuration file
      - ${ORTHANC_CONFIG}:/etc/orthanc/orthanc.json:ro
      # storage volume for raw dicoms
      - ${ORTHANC_DB_MNT}:/var/lib/orthanc/db
    environment:
      # DICOMWeb Plugin
      - DICOM_WEB_PLUGIN_ENABLED=true
      # Postgres Plugin
      - POSTGRESQL_PLUGIN_ENABLED=true
    command: /etc/orthanc/orthanc.json

  postgres:
    image: postgres:13.3-alpine
    container_name: postgres
    restart: always
    volumes:
      - ${POSTGRES_DATA_MNT}:${PGDATA}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=${PGDATA}
      - POSTGRES_DB=orthanc